/*******************************************************************************
 * Copyright (c) Contributors to the Eclipse Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 *******************************************************************************/

package org.osgi.test.assertj.feature;

import java.util.List;
import java.util.Map;

import org.assertj.core.api.InstanceOfAssertFactories;
import org.assertj.core.api.InstanceOfAssertFactory;
import org.assertj.core.api.ListAssert;
import org.assertj.core.api.MapAssert;
import org.osgi.util.feature.Feature;
import org.osgi.util.feature.FeatureBundle;
import org.osgi.util.feature.FeatureConfiguration;
import org.osgi.util.feature.FeatureExtension;

/**
 * Abstract base class for {@link Feature} specific assertions - Generated by
 * CustomAssertionGenerator.
 */
public abstract class AbstractFeatureAssert<S extends AbstractFeatureAssert<S, A>, A extends Feature>
	extends AbstractFeatureArtifactAssert<S, A> {

	/**
	 * Creates a new <code>{@link AbstractFeatureAssert}</code> to make
	 * assertions on actual Feature.
	 *
	 * @param actual the Feature we want to make assertions on.
	 */
	protected AbstractFeatureAssert(A actual, Class<S> selfType) {
		super(actual, selfType);
	}

	@SuppressWarnings("rawtypes")
	static InstanceOfAssertFactory<List, ListAssert<FeatureBundle>>					BUNDLE_LIST		= InstanceOfAssertFactories
		.list(FeatureBundle.class);

	@SuppressWarnings("rawtypes")
	static InstanceOfAssertFactory<Map, MapAssert<String, FeatureConfiguration>>	CONFIG_MAP		= InstanceOfAssertFactories
		.map(String.class, FeatureConfiguration.class);

	@SuppressWarnings("rawtypes")
	static InstanceOfAssertFactory<Map, MapAssert<String, FeatureExtension>>		EXTENSION_MAP	= InstanceOfAssertFactories
		.map(String.class, FeatureExtension.class);

	@SuppressWarnings("rawtypes")
	static InstanceOfAssertFactory<Map, MapAssert<String, String>>					VARIABLE_MAP	= InstanceOfAssertFactories
		.map(String.class, String.class);

	public ListAssert<FeatureBundle> hasBundlesThat() {
		return isNotNull().extracting(f -> f.getBundles(), BUNDLE_LIST)
			.as(actual + ".bundles");
	}

	public MapAssert<String, FeatureConfiguration> hasConfigurationsThat() {
		return isNotNull().extracting(f -> f.getConfigurations(), CONFIG_MAP)
			.as(actual + ".configurations");
	}

	public MapAssert<String, FeatureExtension> hasExtensionsThat() {
		return isNotNull().extracting(f -> f.getExtensions(), EXTENSION_MAP)
			.as(actual + ".extensions");
	}

	public MapAssert<String, String> hasVariablesThat() {
		return isNotNull().extracting(f -> f.getVariables(), VARIABLE_MAP)
			.as(actual + ".variables");
	}

	/**
	 * Verifies that the actual Feature is complete.
	 *
	 * @return this assertion object.
	 * @throws AssertionError - if the actual Feature is not complete.
	 */
	public S isComplete() {
		return isNotNull().is(FeaturesConditions.FeatureConditions.complete());
	}

	/**
	 * Verifies that the actual Feature is not complete.
	 *
	 * @return this assertion object.
	 * @throws AssertionError - if the actual Feature is complete.
	 */
	public S isNotComplete() {
		return isNotNull().isNot(FeaturesConditions.FeatureConditions.complete());
	}

	/**
	 * Verifies that the actual Feature's description is equal to the given one.
	 *
	 * @param description the given description to compare the actual Feature's
	 *            description to.
	 * @return this assertion object.
	 * @throws AssertionError - if the actual Feature's description is not equal
	 *             to the given one.
	 */
	public S hasDescription(String description) {
		return isNotNull().has(FeaturesConditions.FeatureConditions.description(description));
	}

	public S hasDescriptionMatching(String pattern) {
		return isNotNull().has(FeaturesConditions.FeatureConditions.descriptionMatches(pattern));
	}

	public S isDescriptionNull() {
		return isNotNull().is(FeaturesConditions.FeatureConditions.descriptionNull());
	}

	/**
	 * Verifies that the actual Feature's license is equal to the given one.
	 *
	 * @param license the given license to compare the actual Feature's license
	 *            to.
	 * @return this assertion object.
	 * @throws AssertionError - if the actual Feature's license is not equal to
	 *             the given one.
	 */
	public S hasLicense(String license) {
		return isNotNull().has(FeaturesConditions.FeatureConditions.license(license));
	}

	public S hasLicenseMatching(String pattern) {
		return isNotNull().has(FeaturesConditions.FeatureConditions.licenseMatches(pattern));
	}

	public S isLicenseNull() {
		return isNotNull().is(FeaturesConditions.FeatureConditions.licenseNull());
	}

	/**
	 * Verifies that the actual Feature's name is equal to the given one.
	 *
	 * @param name the given name to compare the actual Feature's name to.
	 * @return this assertion object.
	 * @throws AssertionError - if the actual Feature's name is not equal to the
	 *             given one.
	 */
	public S hasName(String name) {
		return isNotNull().has(FeaturesConditions.FeatureConditions.name(name));
	}

	public S hasNameMatching(String pattern) {
		return isNotNull().has(FeaturesConditions.FeatureConditions.nameMatches(pattern));
	}

	public S hasNameNull() {
		return isNotNull().has(FeaturesConditions.FeatureConditions.nameNull());
	}

	/**
	 * Verifies that the actual Feature's vendor is equal to the given one.
	 *
	 * @param vendor the given vendor to compare the actual Feature's vendor to.
	 * @return this assertion object.
	 * @throws AssertionError - if the actual Feature's vendor is not equal to
	 *             the given one.
	 */
	public S hasVendor(String vendor) {
		return isNotNull().has(FeaturesConditions.FeatureConditions.vendor(vendor));
	}

	public S hasVendorMatching(String pattern) {
		return isNotNull().has(FeaturesConditions.FeatureConditions.vendorMatches(pattern));
	}

	public S isVendorNull() {
		return isNotNull().is(FeaturesConditions.FeatureConditions.vendorNull());
	}

	// TODO: categories, copyright, docURL and SCM.

}
